/**
 * Ravimoshark Client API
 * This is an API to interact with Ravimoshark client database. # Introduction This API allow to create, modify and delete addresses and clients. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';


import { Addresses } from '../model/addresses';
import { CustomError } from '../model/customError';
import { Deleted } from '../model/deleted';
import { IdInteger } from '../model/idInteger';
import { InlineResponse200 } from '../model/inlineResponse200';


import { Configuration }                                     from '../configuration';


export interface AddressesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Add one address.
    * Add one address.
    * @param body 
    */
    addAddress(body: Addresses, extraHttpRequestParams?: any): Observable<Addresses>;

    /**
    * Delete one address.
    * Delete one address.
    * @param id id to delete or search
    */
    deleteAddress(id: number, extraHttpRequestParams?: any): Observable<IdInteger>;

    /**
    * Edit one address.
    * Edit one address.
    * @param body 
    */
    editAddress(body: Addresses, extraHttpRequestParams?: any): Observable<Addresses>;

    /**
    * Get one address.
    * Get one address.
    * @param id id to delete or search
    * @param deleted Get all, deleted, not deleted data. Default not deleted.
    */
    getAddressById(id: number, deleted?: Deleted, extraHttpRequestParams?: any): Observable<Addresses>;

    /**
    * Get all addresses.
    * Get all addresses.
    * @param skip number of item to skip
    * @param limit max records to return
    * @param orderBy order by property.
    * @param filterBy filter data.
    * @param deleted Get all, deleted, not deleted data. Default not deleted.
    * @param metadata If metadata is needed (for pagination controls)
    * @param refClient Data from a desired client
    */
    getAddresses(skip?: number, limit?: number, orderBy?: string, filterBy?: string, deleted?: Deleted, metadata?: boolean, refClient?: string, extraHttpRequestParams?: any): Observable<InlineResponse200>;

}
