/**
 * Ravimoshark Client API
 * This is an API to interact with Ravimoshark client database. # Introduction This API allow to create, modify and delete addresses and clients. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';


import { Clients } from '../model/clients';
import { CustomError } from '../model/customError';
import { Deleted } from '../model/deleted';
import { IdInteger } from '../model/idInteger';
import { InlineResponse2001 } from '../model/inlineResponse2001';


import { Configuration }                                     from '../configuration';


export interface ClientsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Add one client.
    * Add one client.
    * @param body 
    */
    addClient(body: Clients, extraHttpRequestParams?: any): Observable<Clients>;

    /**
    * Delete one client.
    * Delete one client.
    * @param refClient id to delete or search
    */
    deleteClient(refClient: string, extraHttpRequestParams?: any): Observable<IdInteger>;

    /**
    * Edit one client.
    * Edit one client.
    * @param body 
    */
    editClient(body: Clients, extraHttpRequestParams?: any): Observable<Clients>;

    /**
    * Get one client.
    * Get one client.
    * @param refClient id to delete or search
    * @param deleted Get all, deleted, not deleted data. Default not deleted.
    */
    getClientById(refClient: string, deleted?: Deleted, extraHttpRequestParams?: any): Observable<Clients>;

    /**
    * Get all clients.
    * Get all clients.
    * @param skip number of item to skip
    * @param limit max records to return
    * @param orderBy order by property.
    * @param filterBy filter data.
    * @param deleted Get all, deleted, not deleted data. Default not deleted.
    * @param metadata If metadata is needed (for pagination controls)
    * @param refClient Data from a desired client
    */
    getClients(skip?: number, limit?: number, orderBy?: string, filterBy?: string, deleted?: Deleted, metadata?: boolean, refClient?: string, extraHttpRequestParams?: any): Observable<InlineResponse2001>;

}
